apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medsync-production

resources:
  - ../../base
  - namespace.yaml
  - postgres-pg-hba-config.yaml

images:
  - name: medsync-api-gateway
    newName: ghcr.io/your-user/medsync-api-gateway
    newTag: vps-production
  - name: medsync-auth-service
    newName: ghcr.io/your-user/medsync-auth-service
    newTag: vps-production
  - name: medsync-users-service
    newName: ghcr.io/your-user/medsync-users-service
    newTag: vps-production
  - name: medsync-patients-service
    newName: ghcr.io/your-user/medsync-patients-service
    newTag: vps-production
  - name: medsync-triage-service
    newName: ghcr.io/your-user/medsync-triage-service
    newTag: vps-production
  - name: medsync-medical-record-service
    newName: ghcr.io/your-user/medsync-medical-record-service
    newTag: vps-production
  - name: medsync-notifications-service
    newName: ghcr.io/your-user/medsync-notifications-service
    newTag: vps-production
  - name: medsync-frontend
    newName: ghcr.io/your-user/medsync-frontend
    newTag: vps-production

replicas:
  - name: frontend
    count: 1
  - name: api-gateway
    count: 1
  - name: auth-service
    count: 1
  - name: users-service
    count: 1
  - name: patients-service
    count: 1
  - name: triage-service
    count: 1
  - name: medical-record-service
    count: 1
  - name: notifications-service
    count: 1

patches:
  - path: patches/resources-frontend.yaml
  - path: patches/resources-api-gateway.yaml
  - path: patches/resources-auth-service.yaml
  - path: patches/resources-users-service.yaml
  - path: patches/resources-patients-service.yaml
  - path: patches/resources-triage-service.yaml
  - path: patches/resources-medical-record-service.yaml
  - path: patches/resources-mongodb.yaml
  - path: patches/resources-notifications-service.yaml
  - path: patches/resources-postgres-users.yaml
  - path: patches/resources-postgres-patients.yaml
  - path: patches/resources-postgres-triage.yaml
  - path: patches/resources-postgres-notifications.yaml
  - path: patches/resources-redis.yaml
  - path: patches/resources-zookeeper.yaml
  - path: patches/resources-kafka.yaml
  - path: patches/resources-prometheus.yaml
  - path: patches/resources-grafana.yaml
  - path: patches/platform-config.yaml
  - path: patches/frontend-config.yaml
  - path: patches/frontend-deployment.yaml
  - path: patches/kafka.yaml
  - path: patches/postgres-users.yaml
  - path: patches/postgres-patients.yaml
  - path: patches/postgres-triage.yaml
  - path: patches/postgres-notifications.yaml
  - path: patches/frontend-service.yaml
    target:
      version: v1
      kind: Service
      name: frontend
  - path: patches/api-gateway-service.yaml
    target:
      version: v1
      kind: Service
      name: api-gateway
