apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pg-hba
data:
  pg_hba.conf: |
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    host    all             all             10.42.0.0/16            scram-sha-256
    host    all             all             10.43.0.0/16            scram-sha-256
    host    all             all             0.0.0.0/0               reject
