package com.medsync.notifications.model;

public enum NotificationType {
    TRIAGE_CREATED,
    TRIAGE_UPDATED,
    TRIAGE_PRIORITY_CHANGED,
    PATIENT_ADDED_TO_QUEUE,
    TRIAGE_STARTED,
    TRIAGE_COMPLETED,
    PATIENT_REFERRED_TO_MEDICAL,
    MEDICAL_STARTED,
    MEDICAL_FINISHED
}
