apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  FRONTEND_URL: http://frontend.production.medsync.local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NEXT_PUBLIC_API_GATEWAY_URL: http://api.production.medsync.local
