apiVersion: apps/v1
kind: Deployment
metadata:
  name: triage-service
spec:
  template:
    spec:
      containers:
        - name: triage-service
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 350m
              memory: 512Mi
