apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medsync-production

resources:
  - ../../base
  - namespace.yaml

images:
  - name: medsync-api-gateway
    newName: ghcr.io/your-user/medsync-api-gateway
    newTag: production
  - name: medsync-auth-service
    newName: ghcr.io/your-user/medsync-auth-service
    newTag: production
  - name: medsync-users-service
    newName: ghcr.io/your-user/medsync-users-service
    newTag: production
  - name: medsync-patients-service
    newName: ghcr.io/your-user/medsync-patients-service
    newTag: production
  - name: medsync-triage-service
    newName: ghcr.io/your-user/medsync-triage-service
    newTag: production
  - name: medsync-notifications-service
    newName: ghcr.io/your-user/medsync-notifications-service
    newTag: production
  - name: medsync-frontend
    newName: ghcr.io/your-user/medsync-frontend
    newTag: production

replicas:
  - name: frontend
    count: 2
  - name: api-gateway
    count: 2
  - name: auth-service
    count: 2
  - name: patients-service
    count: 2
  - name: triage-service
    count: 2
  - name: notifications-service
    count: 2

patches:
  - path: patches/resources-frontend.yaml
  - path: patches/resources-api-gateway.yaml
  - path: patches/resources-auth-service.yaml
  - path: patches/resources-patients-service.yaml
  - path: patches/resources-triage-service.yaml
  - path: patches/resources-notifications-service.yaml
  - path: patches/platform-config.yaml
  - path: patches/frontend-config.yaml
  - path: patches/ingress-frontend.yaml
  - path: patches/ingress-api-gateway.yaml
  - path: patches/ingress-prometheus.yaml
  - path: patches/ingress-grafana.yaml
