apiVersion: v1
kind: Secret
metadata:
  name: application-secrets
type: Opaque
stringData:
  JWT_SECRET: change-me
  INTERNAL_SERVICE_TOKEN: change-me
  ADMIN_EMAIL: admin@medsync.com
  ADMIN_PASSWORD: change-me
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin
