apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medsync-staging

resources:
  - ../../base
  - namespace.yaml

images:
  - name: medsync-api-gateway
    newName: ghcr.io/your-user/medsync-api-gateway
    newTag: staging
  - name: medsync-auth-service
    newName: ghcr.io/your-user/medsync-auth-service
    newTag: staging
  - name: medsync-users-service
    newName: ghcr.io/your-user/medsync-users-service
    newTag: staging
  - name: medsync-patients-service
    newName: ghcr.io/your-user/medsync-patients-service
    newTag: staging
  - name: medsync-triage-service
    newName: ghcr.io/your-user/medsync-triage-service
    newTag: staging
  - name: medsync-medical-record-service
    newName: ghcr.io/your-user/medsync-medical-record-service
    newTag: staging
  - name: medsync-notifications-service
    newName: ghcr.io/your-user/medsync-notifications-service
    newTag: staging
  - name: medsync-frontend
    newName: ghcr.io/your-user/medsync-frontend
    newTag: staging

replicas:
  - name: frontend
    count: 1
  - name: api-gateway
    count: 1
  - name: auth-service
    count: 1
  - name: users-service
    count: 1
  - name: patients-service
    count: 1
  - name: triage-service
    count: 1
  - name: medical-record-service
    count: 1
  - name: notifications-service
    count: 1

patches:
  - path: patches/platform-config.yaml
  - path: patches/frontend-config.yaml
  - path: patches/ingress-frontend.yaml
  - path: patches/ingress-api-gateway.yaml
  - path: patches/ingress-prometheus.yaml
  - path: patches/ingress-grafana.yaml
